# Update system  Ubuntu
#
#
- name: Update the repository cache [Common, Debian family]
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - binutils
    - wget
    - php7.4
    - php7.4-fpm
    - php7.4-mysql
    - nginx
    - build-essential
    - libwrap0-dev
    - libssl-dev
    - python3-distutils
    - mysql-client-core-8.0
- name: Clone efs-utils
  git:
    repo: https://github.com/aws/efs-utils
    dest: ~/efs-utils
    clone: yes
    version: master

- name: Run script
  command: sh build-deb.sh
  args:
    chdir: ~/efs-utils/
  ignore_errors: yes
  
- name: Find deb
  find:
    paths: ~/efs-utils/build
    patterns: '*.deb'
  register: deb_files

- name: Install utils
  apt:
    deb: "{{ item.path }}"
  with_items: "{{ deb_files['files'] }}"
- name: Download py script
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
- name: Run python script
  shell: sudo python3 /tmp/get-pip.py

- name: Install Botocore and PyMySQL
  pip: 
    name: "{{ item }}"
  loop:
    - PyMySQL
    - botocore  

- name: Create dir for unpack
  file:
    state: directory
    path: ~/stunnel-5.63  

- name: Download stunnel
  get_url:
    url: https://www.stunnel.org/downloads/stunnel-5.63.tar.gz
    dest: ~/
- name: Unpack stunnel
  unarchive:
    src: ~/stunnel-5.63.tar.gz
    dest: ~/stunnel-5.63/stunnel-5.63
    remote_src: true

- name: Configure stunnel
  command: sudo  ./configure
  args:
    chdir: ~/stunnel-5.63/stunnel-5.63
- name: Make stunnel
  command: sudo make
  args:
    chdir: ~/stunnel-5.63/stunnel-5.63

- name: Remove old stunnel
  file:
    state: absent
    path: /bin/stunnel

- name: Make install stunnel
  command: sudo make install
  args:
    chdir: ~/stunnel-5.63/stunnel-5.63

- name: Make symlink
  file:
    src: /usr/local/bin/stunnel
    dest: /bin/stunnel
    state: link


